=== clemousse/ProjetDockerXML/annuaire.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<xs:schema xmlns:TSI15="File:///home/gtsi/XML" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="File:///home/gtsi/XML" 
	elementFormDefault="qualified" version="0.0.1">

	<xs:element name="Annuaire">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TSI15:Personne" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="TSI15:Employeur" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="TSI15:lieu" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="quoi" type="xs:string"/>
		</xs:complexType>
	</xs:element>

		<xs:element name="Personne">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="fonction" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="nom" type="xs:string"/>
				<xs:attribute name="prenom" type="xs:string"/>
				<xs:attribute name="service" type="xs:IDREF"/>
				<xs:attribute name="lieu" type="xs:IDREF"/>
			</xs:complexType>
		</xs:element>

		<xs:element name="Employeur">
			<xs:complexType>
				<xs:sequence>
					<xs:element ref="TSI15:direction"/>
				</xs:sequence>
				<xs:attribute name="nom" type="xs:string"/>
			</xs:complexType>
		</xs:element>
					
			<xs:element name="direction">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="TSI15:service"/>
					</xs:sequence>
					<xs:attribute name="nom" type="xs:string"/>
				</xs:complexType>
			</xs:element>

				<xs:element name="service">
					<xs:complexType>
						<xs:attribute name="nom" type="xs:ID"/>
						<xs:attribute name="effectif" type="xs:positiveInteger"/>
					</xs:complexType>
				</xs:element>

		<xs:element name="lieu">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Adresse" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="nom" type="xs:ID"/>
			</xs:complexType>
		</xs:element>

</xs:schema>

=== clemousse/ProjetDockerXML/annuaire.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Annuaire quoi="TSI2015"
	xmlns="File:///home/gtsi/XML"
	xmlns:TSI2015="File:///home/gtsi/XML"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="File:///home/gtsi/XML/annuaire.xsd">

	<Personne nom="pensier" prenom="philemon" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="Amiri" prenom="Mohammed" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="ELJABIRI" prenom="Hanane" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>
	
	<Personne nom="SASYAN" prenom="Valentin" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>
	
	<Personne nom="AIACHE" prenom="Amina" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="Kraus" prenom="Alban" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>
	
	<Personne nom="HOUNTONHADJA" prenom="Maxwell Francis" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="Milville" prenom="Romain" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="LAMGHARI" prenom="HATIM" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="BIH" prenom="imane" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="Chasles" prenom="Clémentine" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Personne nom="Drissi" prenom="Nisrine" service="ENSG" lieu="MLV">
		<fonction>Étudiant</fonction>
	</Personne>

	<Employeur nom="IGN">
		<direction nom="DRE">
			<service nom="ENSG" effectif="13" />
		</direction>
	</Employeur>

	<lieu nom="MLV">
		<Adresse>
			École nationale des sciences géographiques
			6-8 avenue Blaise Pascal – Champs-sur-Marne
			77455 MLV CEDEX 2
		</Adresse>
	</lieu>

</Annuaire>
